### ISSUE TITLE
10s loading lag

### ISSUE THREAD

**Issue by tomByrer** [isomorphic-git/isomorphic-git.github.io#15]
Your web pages load very slow, +10 seconds with Google Fiber connected by Ethernet  At first I thought you were using isomorphic-git in the browser to actually show the pages, so my reaction was, "I don't want to use this laggy library."  Then looking in devtools I find one of your loading JS files was holding everything up: 
`https://wzrd.in/standalone/pify@latest`
![isomorphic-git_20180626_slow-load](https://user-images.githubusercontent.com/1308419/41919169-70656480-7923-11e8-8f00-54a0d08e54d1.png)

Looks like you know how fast jsDelivr is :)  They can [directly source from GitHub & concoct several files into 1 to save on requests](https://www.jsdelivr.com/features).  But seems like you can switch out directly with:
`https://cdn.jsdelivr.net/npm/pify@3.0.0/index.js`

cheers

**Comment by wmhilton** [comment]
Oh huh. I wonder why I'm running `pify` through browserify. Oooooh, yeah so if you look, `pify` doesn't export a UMD module, so even though https://cdn.jsdelivr.net/npm/pify@3.0.0/index.js would be faster it won't work, because it's not written for the browser.

I'll just download it an manually add it to the static folder so we're not relying on wzrd.in service.

**Comment by wmhilton** [comment]
Thanks for the detailed bug report!

**Comment by wmhilton** [comment]
> At first I thought you were using isomorphic-git in the browser to actually show the pages, so my reaction was, "I don't want to use this laggy library."

Well, hopefully that won't be people's *first* impression now. But believe me, it is still pretty darn heavy. I've been working this past two weeks to get the bundlesize down and the processing speed up, but it may still be too slow for many applications. I don't want it to be, and it will continue to get faster and leaner, but it is not at production-level performance yet.
