### ISSUE TITLE
"ReferenceError: pify is not defined"

### ISSUE THREAD

**Issue by tomByrer** [isomorphic-git/isomorphic-git.github.io#16]
Looking at Fx console, I get the error `ReferenceError: pify is not defined` for 
https://github.com/isomorphic-git/isomorphic-git.github.io/blob/d91f9ac55d3a41f765f6e3e2f13970995c4f2b1e/website/static/js/fs.js#L6

For both [cloud versions](https://github.com/isomorphic-git/isomorphic-git.github.io/issues/15).

**Comment by wmhilton** [comment]
Yeah, that's caused by 503 from the CDN hosting pify. If you try again later it will probably work fine. Oh hang on I see your other issue #15 .

**Comment by wmhilton** [comment]
Fixed!
