### ISSUE TITLE
Buttons.js set body white-space to nowrap and it breaks Firefox

### ISSUE THREAD

**Issue by TomasHubelbauer** [isomorphic-git/isomorphic-git.github.io#24]
On top of that the GitHub button ends up being visually broken too in FF.

I'll investigate if this is a (known?) issue with them or if we can work around it.

**Comment by wmhilton** [comment]
Is this the little # of github stars widget? I'm sure we could find a better one than the "official" github one.

**Comment by TomasHubelbauer** [comment]
![image](https://user-images.githubusercontent.com/6831144/42345205-e60224f8-809e-11e8-92da-611724ba81a7.png)

Yeah. It's text is white and it also downloads `buttons.css` asynchronously which messes with the `body`.

**Comment by TomasHubelbauer** [comment]
[This](https://github.com/stretchr/github-stars) might be nice, it uses the user's IP to talk to the GitHub rate-limited API to get the stars. We could rebuilt the design statically and just load in the number. And if the rate limit is exceeded, it's just for that user.

**Comment by TomasHubelbauer** [comment]
Woot I just noticed Zeit covered the suprise charge, I'm super duper glad for that! 🎉 😃

**Comment by wmhilton** [comment]
HA!
```js
HTMLElement.prototype.attachShadow)
```
It's the same issue as https://github.com/isomorphic-git/isomorphic-git.github.io/issues/19. They're attempting to use the Shadow DOM.

**Comment by TomasHubelbauer** [comment]
[Yup](https://github.com/ntkme/github-buttons/blob/master/src/container.coffee#L34). #19 works for me as it probably just doesn't pull any styles and the rest of the shadow DOM features works in latest FF. Maybe it can be worked around by `!important`ing (yeah I said it) the `white-space` on our end so they can't break it and then we can just wait out proper shadow DOM support so it fixes itself in time.

**Comment by wmhilton** [comment]
@TomasHubelbauer Let's build our own Github Star Count!

I've simplified and modernized `stretchr/github-stars`. Here we are:

```js
githubStars = async (repo) =>
  (await fetch(`https://api.github.com/repos/${repo}',
  {headers:{accept:'application/vnd.github.v3+json'}}).then(x => x.json())).stargazers_count
```

**Comment by TomasHubelbauer** [comment]
LOL we don't even need to `!imporant` it because attribute style beats the weakass stylesheet file rule. I'll add it.

**Comment by TomasHubelbauer** [comment]
Sure I'll do that in a separate PR and fix the overflow with the trick above first.

**Comment by TomasHubelbauer** [comment]
🤦‍♂️ (No need to fix this since we are going to be replacing GitHub buttons… Don't mind me…)

**Comment by wmhilton** [comment]
I mean... we could try to fix Github's CSS. But they have all the resources of Microsoft and they still make a bloated `Buttons.js` that could easily have a tracker in there for all we know.

**Comment by wmhilton** [comment]
So I propose we sit on our butt for a day and see if somebody else will fix this problem. 😁 hint hint button breaker

**Comment by wmhilton** [comment]
Unless you feel like making your own. 👌

**Comment by wmhilton** [comment]
Eh... IDK it **is** *really* broken. 🤕 
I think I'll yank the Github Stars widget temporarily.

**Comment by TomasHubelbauer** [comment]
Give me 5 to learn Docusaurus and add our own counter - still good you filed the issue with them though you'll save other sites!

**Comment by wmhilton** [comment]
👍  Alright, I'm hands off! If it doesn't work out, you can merge the [backup plan](https://github.com/isomorphic-git/isomorphic-git.github.io/pull/27).

**Comment by wmhilton** [comment]
![image](https://user-images.githubusercontent.com/587740/42352701-1cd36204-808a-11e8-81a7-464534e7114a.png)

I actually like this even better than what we had before! It's got a consistent look & feel with the other links.
