### ISSUE TITLE
Remove the Try it out section

### ISSUE THREAD

**Issue by TomasHubelbauer** [isomorphic-git/isomorphic-git.github.io#30]
Should we? It won't work without  CORS buster, at least with the placeeholder repo URL. Or we could replace that with one that will work in the browser.

**Comment by wmhilton** [comment]
Hold on. It'll be back soon. 😉 

I need to wait 1 or 2 days to make sure I've stopped whichever server (I *assume* it is `cors-buster`, but it could also be [`webtorrentify-server`](https://www.npmjs.com/package/webtorrentify-server) or even [`signalhub`](https://www.npmjs.com/package/signalhub)) is hogging all the bandwidth. My monthly clock restarted yesterday, and today I was already at 8GB of bandwidth. I've gone through and deleted all the servers that I definitely don't need, and scaled the ones I suspect could be bandwidth heavy to 0 instances.

If tomorrow I'm still at 8GB (it hasn't gone up) then I will flip the switch on a new CORS proxy that is hardcoded to only work for AJAX requests from isomorphic-git.github.io.

Then if that goes alright, I may try loosening the restriction further, to allow any domain as long as they are legit "git" requests. (I still find it hard to fathom 5 terabytes of cloning, so I suspect it was being used for "other" activity.)
