### ISSUE TITLE
Used by not a company

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git.github.io#9]
Can I add my small project GIT Web Terminal to the list? https://jcubic.github.io/git/ . I'm not a company.

**Comment by wmhilton** [comment]
Whoa!!! That's AWESOME! Yeah, totally! PR away 😁

**Comment by wmhilton** [comment]
Holy crap this thing is awesome. I had no idea. I just used `vi` and `git diff` _in my browser!_
